stage('SonarQube Analysis') {
    steps {
        withSonarQubeEnv('SonarQubeServer') {
            bat """
            ${tool 'SonarScanner'}\\bin\\sonar-scanner ^
            -Dsonar.token=${env.SONAR_TOKEN}
            """
        }
    }
}